// <auto-generated />
using System;
using AssuranceApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssuranceApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssuranceApp.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroPermis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("AssuranceApp.Models.ClientRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DateDebutEffet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateFinEffet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateSurvenance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GarantiesSouscrites")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Immatriculation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroContrat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroPermis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroSinistre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClientRecords");
                });

            modelBuilder.Entity("AssuranceApp.Models.DocumentReclamation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ReclamationIdReclamation")
                        .HasColumnType("integer");

                    b.Property<string>("TypeDocument")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Verifie")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ReclamationIdReclamation");

                    b.ToTable("DocumentReclamation");
                });

            modelBuilder.Entity("AssuranceApp.Models.Reclamation", b =>
                {
                    b.Property<int>("IdReclamation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReclamation"));

                    b.Property<int>("Canal")
                        .HasColumnType("integer");

                    b.Property<string>("CommentaireResolution")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DateProblemeDepuis")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateResolution")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateSoumission")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DemarchesDejaEntreprises")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IdAssure")
                        .HasColumnType("integer");

                    b.Property<int?>("IdCompagnie")
                        .HasColumnType("integer");

                    b.Property<int?>("IdContrat")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSinistre")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroPermis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroPolice")
                        .HasColumnType("text");

                    b.Property<string>("NumeroReclamation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroSinistre")
                        .HasColumnType("text");

                    b.Property<string>("Objet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priorite")
                        .HasColumnType("integer");

                    b.Property<string>("ResultatSouhaite")
                        .HasColumnType("text");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<int>("TypeAuteur")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdReclamation");

                    b.ToTable("Reclamations");
                });

            modelBuilder.Entity("AssuranceApp.Models.DocumentReclamation", b =>
                {
                    b.HasOne("AssuranceApp.Models.Reclamation", null)
                        .WithMany("Documents")
                        .HasForeignKey("ReclamationIdReclamation");
                });

            modelBuilder.Entity("AssuranceApp.Models.Reclamation", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
